### ISSUE TITLE
Search for duplicated items

### ISSUE THREAD

**Issue by Leesneaks** [hampusborgos/rme#250]
Is there a way of making it so you can search the map for tiles that contain the two or more of the same time in the tile stack..

I've come across a lot of 3612 (stone) that has like 5 on the same tile.
More just a function for clean up.

**Comment by Elime1** [comment]
We already have a clean map feature. So a first step would probably be to make it remove duplicate walls and grounds as well or have it as an additional option.

But yes, it can be made more advanced with a dialog where you can search for problems according to your settings and then it presents a list with coordinates and information about what the problem is. And then you can decide if you want to "auto fix" them or check the coordinates manually. The map could jump to that problematic location if you click the list item.

**Comment by Mignari** [comment]
Feature added
Select > Find on Selection > Find Duplicated
Edit > Find on Map > Find Duplicated

3ee2d5d2012976328b4a9950655371d730075e05
