### ISSUE TITLE
Remove Duplicated Ids in same SQM option

### ISSUE THREAD

**Issue by elewental** [hampusborgos/rme#331]
some maps in internet has whole cities with each sqm loaded with repeated ids, from 2 to 20.

This tool would be useful to exclude these duplicate ids from all map (or from a specific region)

**Comment by BahamutxD** [comment]
The issue here is how you make a difference between items repeated on purpose and those that are not.

I think that this is more of a map/mapper quality thing that an issue with the editor itself.

**Comment by EPuncker** [comment]
> The issue here is how you make a difference between items repeated on purpose and those that are not.

he is talking about rl maps probably, I've stumbled with this already, and yes, maps live venore and yalahar have A LOT of duplicated items everywhere, almost the entire city! just use browse field in your editor on any wall and you will see.

I think it was a problem with the map tracker since you can't do it with all the items intentionally.

and I agree, a selection tool -> remove duplicated IDs would be nice

**Comment by EPuncker** [comment]
![2021-02-15 18_29_11-Untitled-1 otbm_ - Remere's Map Editor](https://user-images.githubusercontent.com/4684880/107994615-c46d5880-6fbb-11eb-9001-2ed0881e5532.png)

**Comment by EPuncker** [comment]
okay this is a duplicated issue of #250

**Comment by Mignari** [comment]
Feature added
Select > Find on Selection > Find Duplicated
Edit > Find on Map > Find Duplicated

3ee2d5d2012976328b4a9950655371d730075e05
